### ISSUE TITLE
Login con Laravel

### ISSUE THREAD

**Issue by NicoCieri** [NicoCieri/tallerfinal#102]
Ya funciona la conexión entre el server y el front. Todavía no está terminada la funcionalidad del home, estuve viendo este video https://www.youtube.com/watch?v=VkUwaabZK7w para entender como hacerlo, seguí los pasos pero no me está funcionando todavía.

No se olviden de hacer un php artisan migrate. Eliminé la tabla Usuarios y dejé solo la de Users, asi no están duplicadas, y esta no tiene el atributo de la doble password que no es algo que necesitamos. Tratemos de mantener todos los nombres siempre en ingles.

**Comment by AnaMonteleone** [comment]
Subi los cambios sobre Editar usuario el cual todavia no funciona. Deje q siguiera corriendo para ver mas en detalle donde esta el error, asi q por eso aparece lo q hice todo comentado. No recuerdo si pase a este archivo cosas sobre el login, porq tmp tiraba error, asi q a la noche lo sigo viendo eso porq lo habia empezado en un archivo aparte.
